/**
 * GENERATED by `npm run legal` (tools/legal/generate.mjs) from the repository's own legal
 * documents: PRIVACY.md, CREDITS.md, THIRD-PARTY-NOTICES.md, LICENSE, CONTENT-LICENSE.md.
 *
 * Do not hand-edit. Issue #117's acceptance criteria forbid a hand-maintained copy of this
 * content that can drift from the repository sources, and production code may not read a
 * file outside src/ (dependency-direction.test.ts's `escapes src/` rule), so the text
 * arrives here through a generator instead. Edit the markdown and re-run `npm run legal`;
 * tools/legal/generate.test.ts fails until you do.
 */

/** One rendered element of a legal document. The vocabulary is closed; see tools/legal/parse.mjs. */
export type LegalBlock =
  | { readonly kind: 'heading'; readonly level: 2 | 3; readonly text: string }
  | { readonly kind: 'paragraph'; readonly text: string }
  | { readonly kind: 'note'; readonly text: string }
  | { readonly kind: 'code'; readonly text: string }
  | { readonly kind: 'list'; readonly items: readonly string[] }
  | {
      readonly kind: 'table';
      /** The nearest preceding heading: the table's own accessible name. */
      readonly caption: string;
      readonly headers: readonly string[];
      readonly rows: readonly (readonly string[])[];
    };

/** One repository document, offered behind its own disclosure in the About & Legal pane. */
export interface LegalDocument {
  /** Stable id; the disclosure's element ids are built from it. */
  readonly id: string;
  /** The disclosure button's word. UI vocabulary, not document text. */
  readonly label: string;
  /** The repository file this was generated from, shown so a reader can go find it. */
  readonly source: string;
  /** The document's own H1, or `label` when it has none. */
  readonly title: string;
  readonly blocks: readonly LegalBlock[];
}

/** An outbound destination, read out of the document that already states it. */
export interface LegalLink {
  readonly id: string;
  readonly label: string;
  readonly url: string;
}

export const LEGAL_DOCUMENTS: readonly LegalDocument[] = [
  {
    id: 'privacy',
    label: 'Privacy',
    source: 'PRIVACY.md',
    title: 'Privacy Policy',
    blocks: [
      { kind: 'paragraph', text: 'Last updated: 2026-08-25' },
      { kind: 'paragraph', text: 'This policy covers the Tanks! browser game (the "game" or "app"), published at austinorphan.com/tanks/.' },
      { kind: 'heading', level: 2, text: 'Summary' },
      { kind: 'paragraph', text: 'The game collects no data. Nothing leaves your device.' },
      { kind: 'heading', level: 2, text: 'Data the game collects' },
      { kind: 'paragraph', text: 'Nothing. The game does not send any data over the network — no analytics, no telemetry, no API calls. All game data stays on your device.' },
      { kind: 'heading', level: 2, text: 'Data the game stores' },
      { kind: 'paragraph', text: 'The game saves your progress and settings to your device using the browser\'s localStorage. If persistent storage is unavailable, the game stores data in an in-memory backup that expires when the page is closed.' },
      { kind: 'paragraph', text: 'The stored data is organized into the following keys:' },
      {
        kind: 'table',
        caption: 'Data the game stores',
        headers: ['Key', 'Contents'],
        rows: [['tanks.progress.v1', 'Highest level cleared in the campaign'], ['tanks.stats.v1', 'Lifetime and per-attempt game statistics'], ['tanks.run.v2', 'Active campaign run: current level, remaining lives'], ['tanks.custom.v1', 'Chosen tank color and paint customization'], ['tanks.settings.v1', 'Player settings: sound mute and volume, touch control scheme and fire mode, device vibration and controller rumble preferences, motion/flash preference, interface scale'], ['tanks.achievements.v1', 'Earned achievements']],
      },
      { kind: 'paragraph', text: 'tanks.settings.v1 replaces an older tanks.touch.v1 key. The first time you open this version of the game, any touch control settings saved under the old key are copied into the new one and the old key is deleted. The game never writes tanks.touch.v1 again; it is still accepted when importing a save file exported by an older version.' },
      { kind: 'paragraph', text: 'The settings key stores your preferences only. It never records which controllers are connected, their identifiers, their slot numbers, or which player is using which device.' },
      { kind: 'paragraph', text: 'This data is stored entirely in the browser. It never leaves your device and is not transmitted anywhere.' },
      { kind: 'paragraph', text: 'If your browser cannot save data — for example in a private window, or with site storage blocked — the game still runs, and shows a brief on-screen note that settings will not be saved for that session.' },
      { kind: 'paragraph', text: 'You can export and import all of the keys above as a single file, and you can reset your settings back to their defaults. Resetting settings does not affect campaign progress, statistics, or achievements, and resetting progress does not affect settings.' },
      { kind: 'paragraph', text: 'The data is scoped to the game\'s origin: it is accessible only to the origin that serves the game and is unreachable by other sites.' },
      { kind: 'heading', level: 2, text: 'Audio and visuals' },
      { kind: 'paragraph', text: 'Sound is SYNTHESISED. The game builds audio in real time using the Web Audio API. No audio files are downloaded from the network.' },
      { kind: 'paragraph', text: 'Graphics are PROGRAMMED. All visuals are generated in real time via the Canvas API. No external assets (images, models, textures) are downloaded or included.' },
      { kind: 'heading', level: 2, text: 'Third-party services' },
      { kind: 'paragraph', text: 'The game has no third-party integrations. It does not use:' },
      { kind: 'list', items: ['Analytics or tracking services', 'Advertising networks', 'Social media plugins or buttons', 'External APIs, servers, or CDNs', 'Cookies'] },
      { kind: 'paragraph', text: 'The game does use a few browser APIs that may be worth noting:' },
      { kind: 'list', items: ['Gamepad API: Reads connected game controllers for input. This data stays on the device.', 'Web Vibrations API: Provides haptic feedback on supported devices. No data leaves the device.'] },
      { kind: 'heading', level: 2, text: 'Children\'s privacy' },
      { kind: 'paragraph', text: 'The game is designed for all ages. No personal information is collected from any user, including children. This policy is provided to comply with best practices and platform requirements (including the Google Play Developer Policy on app privacy), even though no personal data is collected.' },
      { kind: 'heading', level: 2, text: 'Changes to this policy' },
      { kind: 'paragraph', text: 'If the game\'s privacy practices change, this policy will be updated accordingly.' },
      { kind: 'heading', level: 2, text: 'Contact' },
      { kind: 'paragraph', text: 'For questions about this policy, open an issue on the Tanks! GitHub repository (https://github.com/AustinOrphan/tanks/issues).' },
    ],
  },
  {
    id: 'credits',
    label: 'Credits',
    source: 'CREDITS.md',
    title: 'Audio Credits',
    blocks: [
      { kind: 'paragraph', text: 'No third-party audio assets are currently committed to this repository. public/audio/ contains only a .gitkeep placeholder — there are no .wav files checked in yet.' },
      { kind: 'paragraph', text: 'Because no assets exist, the manifest (src/audio/manifest.ts) declares none, and the engine asks for nothing. It used to declare all ten anyway and let every request 404 — measured against the deployed site, that cost 10 round trips and 93,790 bytes per load, uncached, to rediscover each time that the files were still missing.' },
      { kind: 'paragraph', text: 'What the game plays is unchanged by that, because the synthesised path was already the live one; the difference between effects and music still matters:' },
      { kind: 'list', items: ['Sound effects are SYNTHESISED. play(key) finds no Howl — now because none was ever requested, previously because its load had failed — and builds the sound in src/audio/synth.ts: filtered noise bursts, pitched bodies with falling envelopes, and short transients, layered per key. This is the live path for every effect in the game today. (engine.ts\'s one-oscillator beep remains below it as a floor for any context that cannot support the graph.)', 'Music is GENERATED. music is null because the manifest declares no loop (previously, because its loaderror had fired), so startMusic() falls through to src/audio/music.ts: a slow seeded bass pulse under a sparse drone, scheduled on the audio clock. Until that existed, music was the one thing with no fallback of any kind and the game was simply silent.'] },
      { kind: 'paragraph', text: 'Both are authored as code, which is a deliberate consequence of the policy below: nothing to licence, nothing to verify, and no AI-generated audio.' },
      { kind: 'heading', level: 2, text: 'Licensing policy for future assets' },
      { kind: 'paragraph', text: 'When real audio assets are sourced and committed, they must be dropped into public/audio/ and re-declared in AUDIO_MANIFEST — AUTHORED_LAYOUT in the same file already spells out the expected filenames, and assigning it to AUDIO_MANIFEST is the whole of the switch. They must be:' },
      { kind: 'list', items: ['Royalty-free, CC0 preferred.', 'No AI-generated audio.', 'No audio of unclear or unverified licensing.'] },
      { kind: 'paragraph', text: 'Each asset must be recorded in the attribution table below at the time it is added — including the real source, file, and license. Do not add a row for a file that has not actually been committed.' },
      { kind: 'heading', level: 2, text: 'SFX' },
      {
        kind: 'table',
        caption: 'SFX',
        headers: ['Key', 'File', 'Source', 'License'],
        rows: [],
      },
      { kind: 'heading', level: 2, text: 'Music' },
      {
        kind: 'table',
        caption: 'Music',
        headers: ['File', 'Source', 'License'],
        rows: [],
      },
      { kind: 'paragraph', text: '(Tables intentionally empty — no assets have been sourced yet.)' },
    ],
  },
  {
    id: 'notices',
    label: 'Third-party notices',
    source: 'THIRD-PARTY-NOTICES.md',
    title: 'Third-party notices',
    blocks: [
      { kind: 'paragraph', text: 'This file lists the license of every runtime dependency in package.json\'s "dependencies" (2 at generation time: howler, three) -- the code bundled into npm run build\'s dist/ output. devDependencies are excluded because they are build/test tooling that is never distributed with the built site.' },
      { kind: 'heading', level: 2, text: 'howler@2.2.4 (MIT)' },
      { kind: 'code', text: 'Copyright (c) 2013-2020 James Simpson and GoldFire Studios, Inc.\n\nPermission is hereby granted, free of charge, to any person obtaining\na copy of this software and associated documentation files (the\n"Software"), to deal in the Software without restriction, including\nwithout limitation the rights to use, copy, modify, merge, publish,\ndistribute, sublicense, and/or sell copies of the Software, and to\npermit persons to whom the Software is furnished to do so, subject to\nthe following conditions:\n\nThe above copyright notice and this permission notice shall be\nincluded in all copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,\nEXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND\nNONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE\nLIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION\nOF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION\nWITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.' },
      { kind: 'heading', level: 2, text: 'three@0.169.0 (MIT)' },
      { kind: 'code', text: 'The MIT License\n\nCopyright © 2010-2024 three.js authors\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the "Software"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in\nall copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\nTHE SOFTWARE.' },
    ],
  },
  {
    id: 'license',
    label: 'Code licence',
    source: 'LICENSE',
    title: 'PolyForm Shield License 1.0.0',
    blocks: [
      { kind: 'paragraph', text: 'Required Notice: Copyright Austin Orphan (https://github.com/AustinOrphan/tanks)' },
      { kind: 'paragraph', text: 'https://polyformproject.org/licenses/shield/1.0.0' },
      { kind: 'heading', level: 2, text: 'Acceptance' },
      { kind: 'paragraph', text: 'In order to get any license under these terms, you must agree to them as both strict obligations and conditions to all your licenses.' },
      { kind: 'heading', level: 2, text: 'Copyright License' },
      { kind: 'paragraph', text: 'The licensor grants you a copyright license for the software to do everything you might do with the software that would otherwise infringe the licensor\'s copyright in it for any permitted purpose.  However, you may only distribute the software according to Distribution License and make changes or new works based on the software according to Changes and New Works License.' },
      { kind: 'heading', level: 2, text: 'Distribution License' },
      { kind: 'paragraph', text: 'The licensor grants you an additional copyright license to distribute copies of the software.  Your license to distribute covers distributing the software with changes and new works permitted by Changes and New Works License.' },
      { kind: 'heading', level: 2, text: 'Notices' },
      { kind: 'paragraph', text: 'You must ensure that anyone who gets a copy of any part of the software from you also gets a copy of these terms or the URL for them above, as well as copies of any plain-text lines beginning with Required Notice: that the licensor provided with the software.  For example:' },
      { kind: 'note', text: 'Required Notice: Copyright Yoyodyne, Inc. (http://example.com)' },
      { kind: 'heading', level: 2, text: 'Changes and New Works License' },
      { kind: 'paragraph', text: 'The licensor grants you an additional copyright license to make changes and new works based on the software for any permitted purpose.' },
      { kind: 'heading', level: 2, text: 'Patent License' },
      { kind: 'paragraph', text: 'The licensor grants you a patent license for the software that covers patent claims the licensor can license, or becomes able to license, that you would infringe by using the software.' },
      { kind: 'heading', level: 2, text: 'Noncompete' },
      { kind: 'paragraph', text: 'Any purpose is a permitted purpose, except for providing any product that competes with the software or any product the licensor or any of its affiliates provides using the software.' },
      { kind: 'heading', level: 2, text: 'Competition' },
      { kind: 'paragraph', text: 'Goods and services compete even when they provide functionality through different kinds of interfaces or for different technical platforms.  Applications can compete with services, libraries with plugins, frameworks with development tools, and so on, even if they\'re written in different programming languages or for different computer architectures.  Goods and services compete even when provided free of charge.  If you market a product as a practical substitute for the software or another product, it definitely competes.' },
      { kind: 'heading', level: 2, text: 'New Products' },
      { kind: 'paragraph', text: 'If you are using the software to provide a product that does not compete, but the licensor or any of its affiliates brings your product into competition by providing a new version of the software or another product using the software, you may continue using versions of the software available under these terms beforehand to provide your competing product, but not any later versions.' },
      { kind: 'heading', level: 2, text: 'Discontinued Products' },
      { kind: 'paragraph', text: 'You may begin using the software to compete with a product or service that the licensor or any of its affiliates has stopped providing, unless the licensor includes a plain-text line beginning with Licensor Line of Business: with the software that mentions that line of business.  For example:' },
      { kind: 'note', text: 'Licensor Line of Business: YoyodyneCMS Content Management System (http://example.com/cms)' },
      { kind: 'heading', level: 2, text: 'Sales of Business' },
      { kind: 'paragraph', text: 'If the licensor or any of its affiliates sells a line of business developing the software or using the software to provide a product, the buyer can also enforce Noncompete for that product.' },
      { kind: 'heading', level: 2, text: 'Fair Use' },
      { kind: 'paragraph', text: 'You may have "fair use" rights for the software under the law. These terms do not limit them.' },
      { kind: 'heading', level: 2, text: 'No Other Rights' },
      { kind: 'paragraph', text: 'These terms do not allow you to sublicense or transfer any of your licenses to anyone else, or prevent the licensor from granting licenses to anyone else.  These terms do not imply any other licenses.' },
      { kind: 'heading', level: 2, text: 'Patent Defense' },
      { kind: 'paragraph', text: 'If you make any written claim that the software infringes or contributes to infringement of any patent, your patent license for the software granted under these terms ends immediately. If your company makes such a claim, your patent license ends immediately for work on behalf of your company.' },
      { kind: 'heading', level: 2, text: 'Violations' },
      { kind: 'paragraph', text: 'The first time you are notified in writing that you have violated any of these terms, or done anything with the software not covered by your licenses, your licenses can nonetheless continue if you come into full compliance with these terms, and take practical steps to correct past violations, within 32 days of receiving notice.  Otherwise, all your licenses end immediately.' },
      { kind: 'heading', level: 2, text: 'No Liability' },
      { kind: 'paragraph', text: 'As far as the law allows, the software comes as is, without any warranty or condition, and the licensor will not be liable to you for any damages arising out of these terms or the use or nature of the software, under any kind of legal claim.' },
      { kind: 'heading', level: 2, text: 'Definitions' },
      { kind: 'paragraph', text: 'The licensor is the individual or entity offering these terms, and the software is the software the licensor makes available under these terms.' },
      { kind: 'paragraph', text: 'A product can be a good or service, or a combination of them.' },
      { kind: 'paragraph', text: 'You refers to the individual or entity agreeing to these terms.' },
      { kind: 'paragraph', text: 'Your company is any legal entity, sole proprietorship, or other kind of organization that you work for, plus all its affiliates.' },
      { kind: 'paragraph', text: 'Affiliates means the other organizations than an organization has control over, is under the control of, or is under common control with.' },
      { kind: 'paragraph', text: 'Control means ownership of substantially all the assets of an entity, or the power to direct its management and policies by vote, contract, or otherwise.  Control can be direct or indirect.' },
      { kind: 'paragraph', text: 'Your licenses are all the licenses granted to you for the software under these terms.' },
      { kind: 'paragraph', text: 'Use means anything you do with the software requiring one of your licenses.' },
    ],
  },
  {
    id: 'content-license',
    label: 'Content licence',
    source: 'CONTENT-LICENSE.md',
    title: 'First-party content notice',
    blocks: [
      { kind: 'paragraph', text: 'Copyright Austin Orphan. All rights reserved.' },
      { kind: 'paragraph', text: 'This notice covers the project\'s own content. It does not cover code, and it does not cover third-party material. Three things govern this repository, and every file is under exactly one of them:' },
      {
        kind: 'table',
        caption: 'First-party content notice',
        headers: ['What', 'Governed by'],
        rows: [['Original code, tests and repository tooling', 'LICENSE — PolyForm Shield 1.0.0'], ['First-party content (this notice)', 'All Rights Reserved'], ['Third-party components', 'Their own licenses, recorded in THIRD-PARTY-NOTICES.md']],
      },
      { kind: 'note', text: 'This file records the project\'s licensing boundary. It is not legal advice.' },
      { kind: 'heading', level: 2, text: 'What is reserved' },
      { kind: 'paragraph', text: 'All rights are reserved in the project\'s first-party content, including:' },
      { kind: 'list', items: ['artwork, models, textures and materials;', 'audio, music and sound design;', 'levels, arenas, maps and their layout data;', 'narrative, copy and other written game text;', 'screenshots, captures and promotional media;', 'logos, product names, and other branding.'] },
      { kind: 'paragraph', text: 'Reserved content is not licensed by LICENSE. PolyForm Shield 1.0.0 licenses the software; it grants no rights in the material above. Nothing here is dedicated to the public domain, and no license to reserved content should be inferred from this repository being readable.' },
      { kind: 'heading', level: 2, text: 'Classifying a file' },
      { kind: 'paragraph', text: 'The rules below are meant to settle any file in the tree without guessing. Where two could apply, the more specific one wins.' },
      { kind: 'paragraph', text: 'Third-party first. Anything under node_modules/, and any dependency listed in THIRD-PARTY-NOTICES.md, is governed solely by its own license. That generated file and its verification remain the authoritative third-party notice path — this notice does not restate, override or relicense any of it.' },
      { kind: 'paragraph', text: 'Then reserved content:' },
      {
        kind: 'table',
        caption: 'Classifying a file',
        headers: ['Path', 'Why'],
        rows: [['public/icons/**, public/favicon.svg', 'branding and product marks'], ['public/audio/**', 'audio (no audio is committed today — see CREDITS.md)'], ['src/sim/config/data/arenas.json, campaign.json, versus-catalog.json', 'level, arena and map content'], ['docs/** prose, and screenshots or captures referenced from it', 'narrative, copy and media'], ['Product names and logos wherever they appear', 'branding']],
      },
      { kind: 'paragraph', text: 'Everything else is code, and is licensed under LICENSE: src/ (other than the content data named above), tools/, tests, build configuration, and repository tooling.' },
      { kind: 'paragraph', text: 'Two boundary cases, stated so they are not judgement calls:' },
      { kind: 'list', items: ['Generated output (dist/**, gallery and capture output) inherits the license of whatever it was generated from. A bundle contains both code and reserved content.', 'Data files that are balance rather than content — balance.json, ai-profiles.json, tank-defs.json — are code. They configure behaviour rather than describing a level or a piece of art, and the sim reads them the way it reads any other module.'] },
      { kind: 'heading', level: 2, text: 'Permission' },
      { kind: 'paragraph', text: 'The owner may grant exceptions, commercial licenses, or modding permissions separately. Separately granted written permission overrides the default above. Absent that, assume reserved content is not licensed to you.' },
    ],
  },
];

export const LEGAL_LINKS: readonly LegalLink[] = [
  { id: 'site', label: 'Project website', url: 'https://austinorphan.com/tanks/' },
  { id: 'contact', label: 'Tanks! GitHub repository', url: 'https://github.com/AustinOrphan/tanks/issues' },
];
