/**
 * Renders `src/game/legal-content.ts` from the repository's legal documents (issue #117).
 *
 * Pure string building over `parse.mjs`'s data: generate.mjs writes the result and
 * generate.test.ts compares the committed module against this exact function -- the same
 * regenerate-and-diff idiom as tools/notices/generate.test.ts, tools/devflags/doc.test.ts
 * and tools/tanks/doc.test.ts, applied to a TypeScript module instead of a markdown page.
 *
 * THE TYPES ARE EMITTED HERE, not hand-written beside the data. The block vocabulary is
 * decided by what this generator can produce, so a new block kind has to be added in
 * parse.mjs and here anyway; a hand-written copy of the union in `src/` would be a second
 * place to forget. `src/game/legal.ts` imports both the types and the data from the
 * generated module and does nothing but turn blocks into DOM.
 *
 * Plain node, not vite-node: nothing here imports from src/.
 */
import { legalDocuments, legalLinks, LEGAL_SOURCES } from './parse.mjs';

export const GENERATED_HEADER = `/**
 * GENERATED by \`npm run legal\` (tools/legal/generate.mjs) from the repository's own legal
 * documents: ${LEGAL_SOURCES.map((s) => s.source).join(', ')}.
 *
 * Do not hand-edit. Issue #117's acceptance criteria forbid a hand-maintained copy of this
 * content that can drift from the repository sources, and production code may not read a
 * file outside src/ (dependency-direction.test.ts's \`escapes src/\` rule), so the text
 * arrives here through a generator instead. Edit the markdown and re-run \`npm run legal\`;
 * tools/legal/generate.test.ts fails until you do.
 */`;

/** A TypeScript single-quoted string literal for `value`, newlines escaped. */
function lit(value) {
  const escaped = value
    .split('\\')
    .join('\\\\')
    .split("'")
    .join("\\'")
    .split('\n')
    .join('\\n')
    .split('\r')
    .join('\\r');
  return `'${escaped}'`;
}

function renderBlock(block, indent) {
  const pad = ' '.repeat(indent);
  switch (block.kind) {
    case 'heading':
      return `${pad}{ kind: 'heading', level: ${block.level}, text: ${lit(block.text)} },`;
    case 'paragraph':
      return `${pad}{ kind: 'paragraph', text: ${lit(block.text)} },`;
    case 'note':
      return `${pad}{ kind: 'note', text: ${lit(block.text)} },`;
    case 'code':
      return `${pad}{ kind: 'code', text: ${lit(block.text)} },`;
    case 'list':
      return `${pad}{ kind: 'list', items: [${block.items.map(lit).join(', ')}] },`;
    case 'table':
      return (
        `${pad}{\n` +
        `${pad}  kind: 'table',\n` +
        `${pad}  caption: ${lit(block.caption)},\n` +
        `${pad}  headers: [${block.headers.map(lit).join(', ')}],\n` +
        `${pad}  rows: [${block.rows.map((r) => `[${r.map(lit).join(', ')}]`).join(', ')}],\n` +
        `${pad}},`
      );
    default:
      throw new Error(`tools/legal/render.mjs cannot emit block kind "${block.kind}"`);
  }
}

const TYPES = `/** One rendered element of a legal document. The vocabulary is closed; see tools/legal/parse.mjs. */
export type LegalBlock =
  | { readonly kind: 'heading'; readonly level: 2 | 3; readonly text: string }
  | { readonly kind: 'paragraph'; readonly text: string }
  | { readonly kind: 'note'; readonly text: string }
  | { readonly kind: 'code'; readonly text: string }
  | { readonly kind: 'list'; readonly items: readonly string[] }
  | {
      readonly kind: 'table';
      /** The nearest preceding heading: the table's own accessible name. */
      readonly caption: string;
      readonly headers: readonly string[];
      readonly rows: readonly (readonly string[])[];
    };

/** One repository document, offered behind its own disclosure in the About & Legal pane. */
export interface LegalDocument {
  /** Stable id; the disclosure's element ids are built from it. */
  readonly id: string;
  /** The disclosure button's word. UI vocabulary, not document text. */
  readonly label: string;
  /** The repository file this was generated from, shown so a reader can go find it. */
  readonly source: string;
  /** The document's own H1, or \`label\` when it has none. */
  readonly title: string;
  readonly blocks: readonly LegalBlock[];
}

/** An outbound destination, read out of the document that already states it. */
export interface LegalLink {
  readonly id: string;
  readonly label: string;
  readonly url: string;
}`;

export function renderLegalModule() {
  const documents = legalDocuments();
  const links = legalLinks();

  const docSources = documents
    .map(
      (doc) =>
        `  {\n` +
        `    id: ${lit(doc.id)},\n` +
        `    label: ${lit(doc.label)},\n` +
        `    source: ${lit(doc.source)},\n` +
        `    title: ${lit(doc.title)},\n` +
        `    blocks: [\n${doc.blocks.map((b) => renderBlock(b, 6)).join('\n')}\n    ],\n` +
        `  },`,
    )
    .join('\n');

  const linkSources = links
    .map((link) => `  { id: ${lit(link.id)}, label: ${lit(link.label)}, url: ${lit(link.url)} },`)
    .join('\n');

  return (
    `${GENERATED_HEADER}\n\n${TYPES}\n\n` +
    `export const LEGAL_DOCUMENTS: readonly LegalDocument[] = [\n${docSources}\n];\n\n` +
    `export const LEGAL_LINKS: readonly LegalLink[] = [\n${linkSources}\n];\n`
  );
}
