/**
 * Renders THIRD-PARTY-NOTICES.md's content from package.json's runtime "dependencies" and
 * the license each one ships in node_modules.
 *
 * Pure string building against the filesystem state of node_modules: generate.mjs writes
 * the result and generate.test.ts compares the committed file against this exact function
 * -- the same regenerate-and-diff idiom as tools/devflags/doc.test.ts and
 * tools/tanks/doc.test.ts, applied to a top-level file instead of a docs/ page.
 *
 * devDependencies are excluded BY DESIGN. They are build/test tooling (vite, vitest,
 * typescript, @types/*) that is never bundled into `npm run build`'s dist/ -- only code
 * under package.json's "dependencies" ships with the built site, so only that code's
 * license needs to travel with a distribution (see issue #116).
 *
 * Plain node, not vite-node: unlike tools/devflags and tools/tanks, this module imports
 * nothing from src/ -- only package.json and each dependency's own package.json and
 * LICENSE file under node_modules, all plain filesystem reads with no TypeScript module
 * resolution involved.
 */
import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = fileURLToPath(new URL('../../', import.meta.url));

export const GENERATED_HEADER =
  "<!-- GENERATED by `npm run notices` (tools/notices/generate.mjs) from package.json's\n" +
  "     runtime \"dependencies\" and each package's license file in node_modules.\n" +
  '     Do not hand-edit -- run `npm run notices` after any runtime dependency change. -->\n';

/** Sorted names of package.json's runtime "dependencies" -- NOT devDependencies. */
export function runtimeDependencyNames(pkg) {
  return Object.keys(pkg.dependencies ?? {}).sort();
}

/**
 * Finds a dependency's license file in its node_modules directory. Matches the common
 * spellings ("LICENSE", "LICENSE.md", "LICENSE.txt", any case) rather than one fixed name,
 * since three ships bare "LICENSE" and howler ships "LICENSE.md".
 */
function findLicenseFile(depDir) {
  const entries = readdirSync(depDir).sort();
  const match = entries.find((f) => /^licen[cs]e(\.(md|txt))?$/i.test(f));
  return match ? path.join(depDir, match) : null;
}

function renderDependencySection(name) {
  const depDir = path.join(ROOT, 'node_modules', name);
  const depPkg = JSON.parse(readFileSync(path.join(depDir, 'package.json'), 'utf8'));
  const license =
    typeof depPkg.license === 'string'
      ? depPkg.license
      : (depPkg.license?.type ?? depPkg.licenses?.map((l) => l.type).join(' OR ') ?? 'UNKNOWN');
  const licenseFile = findLicenseFile(depDir);
  if (!licenseFile) {
    throw new Error(
      `no LICENSE file found for runtime dependency "${name}" in node_modules/${name} -- ` +
        'add it to findLicenseFile\'s pattern in tools/notices/render.mjs if this dependency ' +
        'ships one under an unrecognized name',
    );
  }
  const text = readFileSync(licenseFile, 'utf8').trim();
  return `## ${name}@${depPkg.version} (${license})\n\n\`\`\`\n${text}\n\`\`\`\n`;
}

export function renderNotices() {
  const pkg = JSON.parse(readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
  const names = runtimeDependencyNames(pkg);
  const intro =
    `This file lists the license of every runtime dependency in package.json's ` +
    `"dependencies" (${names.length} at generation time: ${names.join(', ')}) -- the code ` +
    "bundled into `npm run build`'s dist/ output. devDependencies are excluded because " +
    'they are build/test tooling that is never distributed with the built site.\n';
  const sections = names.map(renderDependencySection);
  return `${GENERATED_HEADER}\n${intro}\n${sections.join('\n')}`;
}
