/**
 * Renders the README's enemy-roster block from the validated game configuration.
 *
 * Pure string building: generate.mjs writes the block and doc.test.ts compares the
 * committed README against this exact function.
 */
import { arenaById } from '../../src/sim/config/arenas';
import { GAME_BALANCE } from '../../src/sim/config/balance';
import { CAMPAIGN_LEVELS } from '../../src/sim/config/campaign';
import { AIBehavior, TankAbility } from '../../src/sim/config/enums';
import { firstAppearanceFor } from '../../src/sim/config/first-appearance';
import { GAME_TANK_DEFS } from '../../src/sim/config/roster';
import type { TankDefinition } from '../../src/sim/config/types';
import { TANK_KINDS } from '../../src/sim/config/validate';
import type { TankKind } from '../../src/sim/types';

export const ROSTER_START = '<!-- BEGIN GENERATED ENEMY ROSTER -->';
export const ROSTER_END = '<!-- END GENERATED ENEMY ROSTER -->';

function sentenceCase(value: string): string {
  const words = value.toLowerCase().replace(/_/g, ' ');
  return words.charAt(0).toUpperCase() + words.slice(1);
}

function movement(definition: TankDefinition): string {
  const behavior = GAME_BALANCE.aiProfiles[definition.aiProfile].behavior;
  return behavior === AIBehavior.STATIONARY
    ? 'Stationary'
    : sentenceCase(definition.movementSpeed);
}

function mines(definition: TankDefinition): string {
  return definition.abilities.includes(TankAbility.MINE_LAYER)
    ? `Yes (${definition.mineCapacity})`
    : 'No';
}

function shells(definition: TankDefinition): string {
  const bounces = definition.weapon.ricochetCount === 0
    ? 'no bounces'
    : `${definition.weapon.ricochetCount} ${definition.weapon.ricochetCount === 1 ? 'bounce' : 'bounces'}`;
  return [
    sentenceCase(definition.weapon.projectileType),
    `${definition.weapon.fireRate.toLowerCase()} fire`,
    `max ${definition.weapon.maxActiveProjectiles}`,
    bounces,
  ].join('; ');
}

/** The First mission cell for a kind the campaign never spawns: absent, not a number (issue #777). */
export const NOT_IN_CAMPAIGN = 'Not in the campaign';

export function firstMissionCell(appearance: number | null): string {
  return appearance === null ? NOT_IN_CAMPAIGN : String(appearance);
}

/**
 * The roster's row order, with no authored number to sort by (issue #777): earliest first
 * appearance first; kinds that first appear at the same level keep catalog order (the order
 * `kinds` is given in); kinds the campaign never spawns come last, in catalog order.
 */
export function rosterOrder<K extends string>(
  kinds: readonly K[],
  appearance: (kind: K) => number | null,
): K[] {
  const catalog = new Map(kinds.map((kind, i) => [kind, i]));
  return [...kinds].sort((a, b) => {
    const fa = appearance(a);
    const fb = appearance(b);
    if (fa !== fb) {
      if (fa === null) return 1;
      if (fb === null) return -1;
      return fa - fb;
    }
    return (catalog.get(a) as number) - (catalog.get(b) as number);
  });
}

function enemyRows(): string[] {
  const appearance = (kind: TankKind): number | null => firstAppearanceFor(CAMPAIGN_LEVELS, arenaById, kind);
  const enemies = TANK_KINDS.filter((kind) => kind !== 'player');
  return rosterOrder(enemies, appearance).map((kind) => {
    const definition = GAME_TANK_DEFS[kind];
    return `| ${definition.displayName} | ${firstMissionCell(appearance(kind))} | ${movement(definition)} | ${sentenceCase(definition.aiProfile)} | ${mines(definition)} | ${shells(definition)} |`;
  });
}

export function renderEnemyRosterBlock(): string {
  const rows = enemyRows();
  return `${ROSTER_START}
<!-- Generated by \`npm run tanks:doc\`; do not edit this block directly. -->

The canonical roster currently defines ${rows.length} enemy types. Its gameplay data lives in
[\`tank-defs.json\`](src/sim/config/data/tank-defs.json) and
[\`ai-profiles.json\`](src/sim/config/data/ai-profiles.json). First mission is not authored: it is
the earliest level in [\`campaign.json\`](src/sim/config/data/campaign.json) whose arena spawns
that enemy.

| Enemy | First mission | Movement | AI profile | Mines | Shells |
| --- | ---: | --- | --- | --- | --- |
${rows.join('\n')}
${ROSTER_END}`;
}

function occurrences(text: string, needle: string): number {
  return text.split(needle).length - 1;
}

export function replaceEnemyRoster(readme: string): string {
  const starts = occurrences(readme, ROSTER_START);
  const ends = occurrences(readme, ROSTER_END);
  if (starts !== 1 || ends !== 1) {
    throw new Error(
      `README.md must contain exactly one generated enemy-roster block; found ${starts} start marker(s) and ${ends} end marker(s)`,
    );
  }

  const start = readme.indexOf(ROSTER_START);
  const end = readme.indexOf(ROSTER_END, start);
  if (end < start) {
    throw new Error('README.md enemy-roster end marker appears before its start marker');
  }

  return readme.slice(0, start)
    + renderEnemyRosterBlock()
    + readme.slice(end + ROSTER_END.length);
}
