/**
 * Renders the README's enemy-roster block from the validated game configuration.
 *
 * Pure string building: generate.mjs writes the block and doc.test.ts compares the
 * committed README against this exact function.
 */
import { GAME_BALANCE } from '../../src/sim/config/balance';
import { AIBehavior, TankAbility } from '../../src/sim/config/enums';
import { GAME_TANK_DEFS } from '../../src/sim/config/roster';
import type { TankDefinition } from '../../src/sim/config/types';
import { TANK_KINDS } from '../../src/sim/config/validate';

export const ROSTER_START = '<!-- BEGIN GENERATED ENEMY ROSTER -->';
export const ROSTER_END = '<!-- END GENERATED ENEMY ROSTER -->';

function sentenceCase(value: string): string {
  const words = value.toLowerCase().replace(/_/g, ' ');
  return words.charAt(0).toUpperCase() + words.slice(1);
}

function movement(definition: TankDefinition): string {
  const behavior = GAME_BALANCE.aiProfiles[definition.aiProfile].behavior;
  return behavior === AIBehavior.STATIONARY
    ? 'Stationary'
    : sentenceCase(definition.movementSpeed);
}

function mines(definition: TankDefinition): string {
  return definition.abilities.includes(TankAbility.MINE_LAYER)
    ? `Yes (${definition.mineCapacity})`
    : 'No';
}

function shells(definition: TankDefinition): string {
  const bounces = definition.weapon.ricochetCount === 0
    ? 'no bounces'
    : `${definition.weapon.ricochetCount} ${definition.weapon.ricochetCount === 1 ? 'bounce' : 'bounces'}`;
  return [
    sentenceCase(definition.weapon.projectileType),
    `${definition.weapon.fireRate.toLowerCase()} fire`,
    `max ${definition.weapon.maxActiveProjectiles}`,
    bounces,
  ].join('; ');
}

function enemyRows(): string[] {
  return TANK_KINDS
    .filter((kind) => kind !== 'player')
    .sort((a, b) => GAME_TANK_DEFS[a].firstMission - GAME_TANK_DEFS[b].firstMission)
    .map((kind) => {
      const definition = GAME_TANK_DEFS[kind];
      return `| ${definition.displayName} | ${definition.firstMission} | ${movement(definition)} | ${sentenceCase(definition.aiProfile)} | ${mines(definition)} | ${shells(definition)} |`;
    });
}

export function renderEnemyRosterBlock(): string {
  const rows = enemyRows();
  return `${ROSTER_START}
<!-- Generated by \`npm run tanks:doc\`; do not edit this block directly. -->

The canonical roster currently defines ${rows.length} enemy types. Its gameplay data lives in
[\`tank-defs.json\`](src/sim/config/data/tank-defs.json) and
[\`ai-profiles.json\`](src/sim/config/data/ai-profiles.json).

| Enemy | First mission | Movement | AI profile | Mines | Shells |
| --- | ---: | --- | --- | --- | --- |
${rows.join('\n')}
${ROSTER_END}`;
}

function occurrences(text: string, needle: string): number {
  return text.split(needle).length - 1;
}

export function replaceEnemyRoster(readme: string): string {
  const starts = occurrences(readme, ROSTER_START);
  const ends = occurrences(readme, ROSTER_END);
  if (starts !== 1 || ends !== 1) {
    throw new Error(
      `README.md must contain exactly one generated enemy-roster block; found ${starts} start marker(s) and ${ends} end marker(s)`,
    );
  }

  const start = readme.indexOf(ROSTER_START);
  const end = readme.indexOf(ROSTER_END, start);
  if (end < start) {
    throw new Error('README.md enemy-roster end marker appears before its start marker');
  }

  return readme.slice(0, start)
    + renderEnemyRosterBlock()
    + readme.slice(end + ROSTER_END.length);
}
